apiVersion: v1
kind: ServiceAccount
metadata:
  name: restarter
  namespace: paasdocs-preview
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: run-pod-restart
subjects:
  - kind: ServiceAccount
    name: restarter
    namespace: paasdocs-preview
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: tutorials-rollout-restart-cronjob
  namespace: paasdocs-preview
spec:
  schedule: "*/30 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: restarter
          containers:
            - name: tutorials-rollout-restart-job
              image: bitnami/kubectl:1.20
              command: ['kubectl', 'rollout' ,'restart', 'deployment/ocitutorials-preview', '-n', 'paasdocs-preview']
          restartPolicy: OnFailure